service: tasks-backup-api
frameworkVersion: '2'

provider:
  name: aws
  runtime: java8
  region: eu-west-2
  profile: serverless

  environment:
   DB_HOST: ${file(./config.dev.json):DB_HOST}
   DB_NAME: ${file(./config.dev.json):DB_NAME}
   DB_USER: ${file(./config.dev.json):DB_USER}
   DB_PASSWORD: ${file(./config.dev.json):DB_PASSWORD}
    
package:
  artifact: target/more-clean-water-dev.jar
functions:

 # API for the purpose of learning different approaches of architecture
  tasks-api: 
    handler: com.techreturners.mcw.learning.Handler # Reference to class handler
    events: # All events associated with this function
      - http:
          path: tasks/getall
          method: get
      - http:
          path: tasks/create
          method: post
      - http:
          path: tasks/update/{user_id}
          method: put
          request:
            parameters:
              paths:
                user_id: true
      - http:
          path: tasks/delete/{delId}
          method: delete
          request:
            parameters:
              paths:
                delid: true

# APIs for User Management Module
  users-list-api: 
    handler: com.techreturners.mcw.handler.UserListHandler # Reference to class handler
    events: # Get the user list
      - http:
          path: /users/list
          method: get
          cors: true # <-- CORS!
  users-get-api:
    handler: com.techreturners.mcw.handler.UserInfoHandler # Reference to class handler
    events: # Get the specific user details
      - http:
          path: /users/{userId}
          method: get
          cors: true # <-- CORS!
  users-add-api:
    handler: com.techreturners.mcw.handler.UserAddHandler # Reference to class handler
    events: # Create user
      - http:
          path: /users/add
          method: post
          cors: true # <-- CORS!
  users-edit-api:
    handler: com.techreturners.mcw.handler.UserEditHandler # Reference to class handler
    events: # Update user
      - http:
          path: /users/edit/{userId}
          method: put
          cors: true # <-- CORS!
  users-deactivate-api:
    handler: com.techreturners.mcw.handler.UserDeleteHandler # Reference to class handler
    events: # Deactivate user
      - http:
          path: /users/delete/{userId}
          method: get
          cors: true # <-- CORS!
  login-user-api: 
    handler: com.techreturners.mcw.handler.UserLoginHandler # Reference to class handler
    events: # Get the user list
      - http:
          path: /users/login
          method: put
          cors: true # <-- CORS!

  # APIs for Station Management Module
  stations-list-api: 
    handler: com.techreturners.mcw.handler.StationListHandler # Reference to class handler
    events: # Get the user list
      - http:
          path: /stations/list
          method: get
  stations-add-api:
    handler: com.techreturners.mcw.handler.StationAddHandler # Reference to class handler
    events: # Create user
      - http:
          path: /stations/add
          method: post
  stations-edit-api:
    handler: com.techreturners.mcw.handler.StationEditHandler # Reference to class handler
    events: # Update user
      - http:
          path: /stations/edit/{stationId}
          method: put
  stations-disable-api:
    handler: com.techreturners.mcw.handler.StationDisableHandler # Reference to class handler
    events: # Deactivate user
      - http:
          path: /stations/delete/{stationId}
          method: get

# APIs for Awareness Management Module
  sections-list-api: 
    handler: com.techreturners.mcw.handler.SectionListHandler # Reference to class handler
    events: # Get the user list
      - http:
          path: /sections/list
          method: get
          cors: true # <-- CORS!
  sections-add-api:
    handler: com.techreturners.mcw.handler.SectionAddHandler # Reference to class handler
    events: # Create user
      - http:
          path: /sections/add
          method: post
          cors: true # <-- CORS!
  sections-disable-api:
    handler: com.techreturners.mcw.handler.SectionDeleteHandler # Reference to class handler
    events: # Deactivate user
      - http:
          path: /sections/delete/{id}
          method: delete
          cors: true # <-- CORS!

# APIs for Mics Services

  county-list-api: 
    handler: com.techreturners.mcw.handler.CountyListHandler # Reference to class handler
    events: # Get the user list
      - http:
          path: /county/list
          method: get
          cors: true # <-- CORS!
  deactivate-user-api: 
    handler: com.techreturners.mcw.handler.DeactivateUserHandler # Reference to class handler
    events: # Get the user list
      - http:
          path: /users/deactivate/{userId}
          method: delete
          cors: true # <-- CORS!
  unsubscribe-user-api: 
    handler: com.techreturners.mcw.handler.UnsubscribeUser # Reference to class handler
    events: # Get the user list
      - http:
          path: /users/unsubscribe/{userId}
          method: put
          cors: true # <-- CORS!
